name: CI

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push'
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@master

  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile

  #     - name: Test
  #       env:
  #         CI: true
  #       run: yarn test

  # When a pull_request is created or synchronized, deploy a preview to Netlify
  deployDraftBuildToDev:
    name: Deploy draft build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy draft build to Netlify
        uses: South-Paw/action-netlify-deploy@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_DEV_SITE_ID }}
          build-dir: './build'
          draft: true
          comment-on-pull-request: true

  # Upon a push to the master branch, deploy a build to Netlify
  deployBuildToDev:
    name: Deploy build to development
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy dev build to Netlify
        uses: South-Paw/action-netlify-deploy@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_DEV_SITE_ID }}
          build-dir: './build'
          comment-on-commit: true
